class CancelledError(Exception):
    """The Future or Task was cancelled."""
